spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:belongDb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    change-log: classpath:/db/changelog.xml
    contexts: deployed,seed

springdoc:
  api-docs:
    path: /api-docs

belong.api.key: 'hRGkLDWkhSe0aie6q2pKnhd7cx8gvNoY1mfuAW5eYR5llFEqAzq243f6cLlAfvXRzVY7swFVv80jl2qSLxOEIzH0V3NoM75QEWq0UaI3tJmui4KCcriOE5nNMmVqUBFt'